version: '3'

services:
  todotests:
    depends_on:
      - 'todofront'
      - 'todoback'
    image: todotests:latest
    environment:
      FRONT_HOST: todofront
      FRONT_PORT: 3000
    restart: on-failure

  todofront:
    depends_on:
      - 'todoback'
    image: todofrontend:latest
    environment:
      REACT_APP_API_HOST: todoback
      REACT_APP_API_PORT: 3001
    ports:
      - '3000:3000'
    restart: always

  todoback:
    image: todobackend:latest
    ports:
      - '3001:3001'
    restart: always
